//LocalHost
##Gets All Contacts

//GET http://localhost:8080/contacts/

##Get Contacts by ID

//GET http://localhost:8080/contacts/67cfb9dccbb49c8d9f835e9f


## Create Contact

# POST http://localhost:8080/contacts/ HTTP/1.1
# Content-Type: application/json

# {
#     "firstName": "shifaula",
#     "lastName": "zomapeee",
#     "email": "shifau@byupathway.edu",
#     "favoriteColor": "pink",
#     "birthday": "09.10.1990"
# }

# # PUT contact

# PUT http://localhost:8080/contacts/67e36130070f2e60a8dc6325/ HTTP/1.1
# Content-Type: application/json

# {
#     "firstName": "narrak",
#     "lastName": "ooobanaa",
#     "email": "brbama@byupathway.edu",
#     "favoriteColor": "blue",
#     "birthday": "09.10.1990"
# }

## DELETE contact

//DELETE http://localhost:8080/contacts/67e36130070f2e60a8dc6325