//LocalHost
##Gets All Contacts

//GET http://localhost:8080/contacts/

##Get Contacts by ID

//GET http://localhost:8080/contacts/67e36130070f2e60a8dc6325


## Create Contact

# POST http://localhost:8080/contacts/ HTTP/1.1
# Content-Type: application/json

# {
#     "firstName": "shifaula",
#     "lastName": "zomapeee",
#     "email": "shifau@byupathway.edu",
#     "favoriteColor": "pink",
#     "birthday": "09.10.1990"
# }

# # PUT contact

# PUT http://localhost:8080/contacts/67e3799131d4c628fa01c0d0/ HTTP/1.1
# Content-Type: application/json

# {
#     "firstName": "zombie",
#     "lastName": "zomapeeer",
#     "email": "zoomm@byupathway.edu",
#     "favoriteColor": "pink",
#     "birthday": "09.10.1991"
# }

## DELETE contact

//DELETE http://localhost:8080/contacts/67e37689bd2eb54e368a1318